title: Lavesh Gupta # your name (or website title) here
logo: "/images/dp.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello! I'm an Electrical Engineering undergrad at IIT Kanpur. Presently, I am in my third year of college. 
  <br><br>
  I am interested in programming, finance, and machine learning. Currently, I'm learning Data Structures & Algorithms. Thank you for visiting! 
  <br><br>
  <a href="https://www.linkedin.com/in/lavesh-gupta/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-PGK07RWDPW # your Google Analytics tracking ID here
